<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var $block Magenest\Test1\Block\PostCollection
 */

$collection = $block->getPostsWithActorAndDirectoryData();
?>
<div class="table-wrapper orders-history">
    <table class="data table table-order-items history" id="my-orders-table">
        <caption class="table-caption"><?= __('Grid Record') ?></caption>
        <thead>
        <tr>
            <th scope="col" class="col movie"><?= __('Movies') ?></th>
            <th scope="col" class="col director"><?= __('Director') ?></th>
            <th scope="col" class="col actor"><?= __('Actors') ?></th>
        </tr>
        </thead>
        <tbody>
        <?php
        foreach ($collection as $item): ?>
            <tr>
                <td data-th="<?= $block->escapeHtml(__('Movies')) ?>" class="col movie"><?= $item->getMovie() ?></td>
                <td data-th="<?= $block->escapeHtml(__('Director')) ?>" class="col director"><?= $item->getDirector() ?></td>
                <td data-th="<?= $block->escapeHtml(__('Actors')) ?>" class="col actor"><?= $item->getActor() ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>
