<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

// phpcs:disable Magento2.Templates.ThisInTemplate

/** @var $block \Magento\Sales\Block\Order\Email\Items\DefaultItems */

/** @var $_item \Magento\Sales\Model\Order\Item */
$_item = $block->getItem();
$_order = $_item->getOrder();
$_store = $_order->getStore();

$_imageHelper = \Magento\Framework\App\ObjectManager::getInstance()->get('Magento\Catalog\Helper\Image');
$_baseImageUrl = $_store->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA) . 'catalog/product';
?>
<tr>
    <td class="item-info<?= ($block->getItemOptions() ? ' has-extra' : '') ?>" colspan="2" style="padding:20px 20px 10px;">
        <p style="font-size:18px;font-weight:600;  margin-bottom: 10px;">Information</p>
        <p style="font-size:18px;font-weight:600; color:#da0f0f;margin-bottom: 10px;">Installation (Expected delivery date: <?= date_format(date_create($_order->getCreatedAt()), 'd/m/Y') ?>)</p>
        <table style="width:100%;">
            <tr>
                <td class="item-img" width="120">
                    <img src="<?= $_imageHelper->init($_item->getProduct(), 'small_image', ['type'=>'small_image'])->keepAspectRatio(true)->resize('65','65')->getUrl();?>" alt="<?= __('Product Image');?>">
                </td>
                <td>
                    <p class="sku" style="font-size:16px;  margin-bottom: 5px;"><?= $block->escapeHtml(__('SKU')) ?>: <?= $block->escapeHtml($block->getSku($_item)) ?></p>
                    <p class="product-name"><?= $block->escapeHtml($_item->getName()) ?></p>
                    <?php if ($block->getItemOptions()): ?>
                        <dl class="item-options">
                            <?php foreach ($block->getItemOptions() as $option): ?>
                                <?php if ($block->escapeHtml($option['label']) != 'objet_sales_combine_id'): ?>
                                    <?php if ($block->escapeHtml($option['label']) != 'objet_sales_options'): ?>
                                        <dt><strong><em><?= $block->escapeHtml($option['label']) ?></em></strong></dt>
                                    <?php endif; ?>
                                    <dd>
                                        <?= /* @noEscape */
                                        nl2br($block->escapeHtml($option['value'])) ?>
                                    </dd>
                                <?php endif; ?>
                            <?php endforeach; ?>
                        </dl>
                    <?php endif; ?>
                    <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
                    <?php if ($addInfoBlock): ?>
                        <?= $addInfoBlock->setItem($_item)->toHtml() ?>
                    <?php endif; ?>
                    <p class="product-qty">Qty : <?= (float)$_item->getQtyOrdered() ?>
                        <?= /* @noEscape */
                        $block->getItemPrice($_item) ?>
                    </p>
                </td>
            </tr>
        </table>
    </td>
</tr>
<?php if ($_item->getGiftMessageId()
    && $_giftMessage = $this->helper(\Magento\GiftMessage\Helper\Message::class)
        ->getGiftMessage($_item->getGiftMessageId())
): ?>
    <tr>
        <td colspan="3" class="item-extra">
            <table class="message-gift">
                <tr>
                    <td>
                        <h3><?= $block->escapeHtml(__('Gift Message')) ?></h3>
                        <strong><?= $block->escapeHtml(__('From:')) ?></strong> <?= $block->escapeHtml($_giftMessage->getSender()) ?>
                        <br/><strong><?= $block->escapeHtml(__('To:')) ?></strong> <?= $block->escapeHtml($_giftMessage->getRecipient()) ?>
                        <br/><strong><?= $block->escapeHtml(__('Message:')) ?></strong>
                        <br/><?= $block->escapeHtml($_giftMessage->getMessage()) ?>
                    </td>
                </tr>
            </table>
        </td>
    </tr>
<?php endif; ?>
