<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /** @var \Magento\Sales\Block\Adminhtml\Items\Column\DefaultColumn $block */ ?>
<?php $_item = $block->getItem() ?>

<?php
    $name = [];
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $customerRepository = $objectManager->get(\Magento\Customer\Api\CustomerRepositoryInterface::class);
    $customer_id = $_item->getData('customer_id');
    if ($customer_id) {
        $customer = $customerRepository->getById($customer_id);
        $name = $customer->getFirstname() . ' ' . $customer->getLastname();
    } else {
        $name = '';
    }
?>

<div>
    <?= /* @noEscape */ $name ?>
</div>
